# Generated by Django 5.2 on 2025-07-08 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgname', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Anekal', 'Anekal'), ('Anjanapura', 'Anjanapura'), ('Arekere', 'Arekere'), ('Attibele', 'Attibele'), ('Balepet', 'Balepet'), ('Banashankari', 'Banashankari'), ('Banaswadi', 'Banaswadi'), ('Basavanagudi', 'Basavanagudi'), ('Basaveshwaranagar', 'Basaveshwaranagar'), ('Begur', 'Begur'), ('Bellandur', 'Bellandur'), ('Bommanahalli', 'Bommanahalli'), ('Bommasandra', 'Bommasandra'), ('BTM Layout', 'BTM Layout'), ('Chandapura', 'Chandapura'), ('Chickpet', 'Chickpet'), ('Chikkabanavara', 'Chikkabanavara'), ('Cottonpet', 'Cottonpet'), ('CV Raman Nagar', 'CV Raman Nagar'), ('Domlur', 'Domlur'), ('Electronic City', 'Electronic City'), ('Fraser Town (Pulakeshi Nagar)', 'Fraser Town (Pulakeshi Nagar)'), ('Girinagar', 'Girinagar'), ('Gottigere', 'Gottigere'), ('Hebbal', 'Hebbal'), ('HBR Layout', 'HBR Layout'), ('Hesaraghatta', 'Hesaraghatta'), ('Hoodi', 'Hoodi'), ('Horamavu', 'Horamavu'), ('HSR Layout', 'HSR Layout'), ('Hulimavu', 'Hulimavu'), ('Indiranagar', 'Indiranagar'), ('J. P. Nagar', 'J. P. Nagar'), ('Jalahalli', 'Jalahalli'), ('Jayanagar', 'Jayanagar'), ('Jigani', 'Jigani'), ('Kalyan Nagar', 'Kalyan Nagar'), ('Kamakshipalya', 'Kamakshipalya'), ('Kammanahalli', 'Kammanahalli'), ('Kengeri', 'Kengeri'), ('Koramangala', 'Koramangala'), ('Kothnur', 'Kothnur'), ('Krishnarajapuram', 'Krishnarajapuram'), ('Kumaraswamy Layout', 'Kumaraswamy Layout'), ('Lingarajapuram', 'Lingarajapuram'), ('Madiwala', 'Madiwala'), ('Mahalakshmi Layout', 'Mahalakshmi Layout'), ('Mahadevapura', 'Mahadevapura'), ('Malleswaram', 'Malleswaram'), ('Marathahalli', 'Marathahalli'), ('Mathikere', 'Mathikere'), ('Nagarbhavi', 'Nagarbhavi'), ('Nandini Layout', 'Nandini Layout'), ('Nayandahalli', 'Nayandahalli'), ('Nelamangala', 'Nelamangala'), ('Padmanabhanagar', 'Padmanabhanagar'), ('Peenya', 'Peenya'), ('Pete Area (Chickpet, Balepet, Cottonpet, Sultanpet)', 'Pete Area (Chickpet, Balepet, Cottonpet, Sultanpet)'), ('R. T. Nagar', 'R. T. Nagar'), ('Rajarajeshwari Nagar', 'Rajarajeshwari Nagar'), ('Rajajinagar', 'Rajajinagar'), ('Ramamurthy Nagar', 'Ramamurthy Nagar'), ('Sadashivanagar', 'Sadashivanagar'), ('Sarjapura', 'Sarjapura'), ('Seshadripuram', 'Seshadripuram'), ('Shivajinagar', 'Shivajinagar'), ('Sultanpet', 'Sultanpet'), ('Thavarekere', 'Thavarekere'), ('Ulsoor (Halasuru)', 'Ulsoor (Halasuru)'), ('Uttarahalli', 'Uttarahalli'), ('Varthur', 'Varthur'), ('Vasanth Nagar', 'Vasanth Nagar'), ('Vidyaranyapura', 'Vidyaranyapura'), ('Vijayanagar', 'Vijayanagar'), ('Whitefield', 'Whitefield'), ('Yelahanka', 'Yelahanka'), ('Yeshwanthpur', 'Yeshwanthpur')], max_length=100)),
                ('bathroom_type', models.CharField(choices=[('common', 'Common Bathrooms'), ('attached', 'Attached Bathrooms'), ('both', 'Both')], max_length=10)),
                ('washing_machine', models.BooleanField(default=False)),
                ('water_heater', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('languageknown1', models.CharField(blank=True, max_length=50)),
                ('languageknown2', models.CharField(blank=True, max_length=50)),
                ('languageknown3', models.CharField(blank=True, max_length=50)),
                ('two_sharing', models.BooleanField(default=False)),
                ('vacancy2', models.IntegerField(blank=True, null=True)),
                ('fees2', models.IntegerField(blank=True, null=True)),
                ('three_sharing', models.BooleanField(default=False)),
                ('vacancy3', models.IntegerField(blank=True, null=True)),
                ('fees3', models.IntegerField(blank=True, null=True)),
                ('four_sharing', models.BooleanField(default=False)),
                ('vacancy4', models.IntegerField(blank=True, null=True)),
                ('fees4', models.IntegerField(blank=True, null=True)),
                ('other_sharing', models.BooleanField(default=False)),
                ('vacancy', models.IntegerField(blank=True, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('phno', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PGImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pg_images/')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.pginformation')),
            ],
        ),
    ]
