# Generated by Django 5.1.7 on 2025-07-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pginformation',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='pginformation',
            name='password',
        ),
    ]
